### ISSUE TITLE
No bold accidentals?

### ISSUE THREAD

**Issue by marsdeat** [MuseScoreFonts/Edwin#11]
I assume this is just a 'this hasn't been implemented yet' thing, but got very confused when my chord symbols randomly lost their accidentals today in MU4a, and it turns out Edwin Bold's accidentals symbols are populated as characters in the font table but are blank, and wanted to make sure this is known behaviour.
![Bold](https://user-images.githubusercontent.com/14811708/163725558-e2655798-8dfe-4dbd-827e-9425386c0e10.png)
![Regular](https://user-images.githubusercontent.com/14811708/163725575-19ac9869-114f-494d-8bee-6f7ddf14d175.png)

**Comment by oktophonie** [comment]
You're quite right! Not sure why these symbols are blank (same problem in the italics); I am now investigating.

**Comment by Jojo-Schmitz** [comment]
This seems to be a regression vs. (the Edwin version distributed along with) MuseScore 3.6.2

**Comment by ghost** [comment]
Reinstated in [v0.54](https://github.com/MuseScoreFonts/Edwin/releases/tag/v0.54)
