### ISSUE TITLE
Missing typographic apostrophe

### ISSUE THREAD

**Issue by samarutuk** [MuseScoreFonts/Edwin#3]
There seems to be no typographic apostrophe in Edwin (see red circle in the attached example). However, the apostrophe is immensely important for lyrics and should look like a comma (see also https://en.wikipedia.org/wiki/Apostrophe). For the typographic apostrophe I created an extra key combination (German keyboard modified with Microsoft Keyboard Layout Creator (MSKLC)) which works perfectly with other fonts, so it is not a typo. Please check in the future for new fonts if the default characters are complete, otherwise a release makes no sense and only makes complainers like me crawl out of their holes 😉
Nevertheless, I'm glad that there is now an alternative to Free Serif, which just isn't really any good for a font in music notation. You should think about adding more font styles (see, for example, the styles of the freely available Alegreya), possibly including an SC variant, since this typographic feature is not supported out of the box in MuseScore. Such styles are enormously important for good and, above all, attractive music notation.

Example from lyrics:
![Edwin Missing Apostrophe_Screenshot 2021-02-12 122335](https://user-images.githubusercontent.com/46650176/107847945-22e5db80-6df0-11eb-96ea-1140e9385474.png)

**Comment by oktophonie** [comment]
The character you are looking for exists in Edwin as U+2019 (quoteright), and is accessible from the Special Characters palette. Or are you suggesting something else?

**Comment by samarutuk** [comment]
Yes, that would be the actual typographic apostrophe/right quotation mark (U+2019). In the Anglo-Saxon world, the typewriter apostrophe (') is probably more commonly used, but in German the typographic one should be used, so the character is important. I have a modified German keyboard layout (Windows) for this. On the Mac, the character is there by default.
But when I use the key combination for the typographic apostrophe in lyric or text input mode, this character ʼ appears (see also example above). Looks like it is U+2019 from a sans-serif font.  There are no problems with other fonts. Maybe it is because Edwin is not installed through the OS? In any case, when typing lyrics you can't always open the Special Characters palette. 
Here is an example of professionally set notes using the typesetter's apostrophe:
![Screenshot 2021-02-15 144230](https://user-images.githubusercontent.com/46650176/108040179-48b3f000-703d-11eb-9508-5e06cc872999.png)

**Comment by samarutuk** [comment]
I passed the ball back to the MuseScore developers. U+2019 works flawlessly on the Mac. It seems to be an issue with the Windows version of MuseScore.

This is off-topic, I know, but would you consider more font styles? Like the ones listed in my previous post?

**Comment by oktophonie** [comment]
I'll close this issue here if we can consider it a MuseScore issue rather than Edwin specifically; thanks for your investigations!
I would like more styles in time. This is only the beginning :) I'd particularly like to see a Semibold weight personally.
