### ISSUE TITLE
MacOS FontBook Validation

### ISSUE THREAD

**Issue by snakebyte69** [MuseScoreFonts/Edwin#4]
1 serious error was found. Do not use this font file.

Glyphs 3 reports this - "No Name Table"

I'm sure it's some annoying Apple requirement that's an easy fix.

<img width="624" alt="Screen Shot 2021-02-14 at 6 03 31 pm" src="https://user-images.githubusercontent.com/39090848/107870737-2c09a200-6eef-11eb-9a6a-cf4e074d353c.png">

**Comment by oktophonie** [comment]
@snakebyte69 If you have a moment, could you perhaps test whether the latest release (0.52) still suffers from this problem?

**Comment by snakebyte69** [comment]
I've tested again with the new version v0.52.
I works fine now, cheers!

**Comment by oktophonie** [comment]
Thank you! :)
