### ISSUE TITLE
The string "Nr." turns into "№"

### ISSUE THREAD

**Issue by Jojo-Schmitz** [MuseScoreFonts/Edwin#5]
See https://github.com/musescore/MuseScore/issues/8161

![image](https://user-images.githubusercontent.com/1786669/120501074-9ae90900-c3c1-11eb-9c27-6e93de602944.png)

![image](https://user-images.githubusercontent.com/1786669/120501097-9fadbd00-c3c1-11eb-9ae6-1a502d8bc847.png)

**Comment by maximebochon** [comment]
It does not look like an issue at all. It's a proof of high quality font. It's even a blessing that an open-source font provides such ligatures.

I advise to take a look at the wikipedia page if you are not acustomed to the typographical notion of ligatures: https://en.wikipedia.org/wiki/Ligature_(writing)

**Comment by maximebochon** [comment]
There is a user workaround consisting in placing a "non-joiner character" between characters you don't want ligatures to apply on. See here for details: https://en.wikipedia.org/wiki/Zero-width_non-joiner

**Comment by maximebochon** [comment]
In the context of a piece of software displaying text, there is probably an option to enable/disable ligatures provided by the font rendering engine. But I don't know for sure.

**Comment by oktophonie** [comment]
Most commonly this № ligature is used in Russian (occasionally elsewhere but not often): https://en.wikipedia.org/wiki/Numero_sign

Given that converting Nr. into № is presumably _not_ wanted more often than not, it may be wisest to remove this ligature definition; the glyph remains, so it can be inserted manually when people want it.

Does MuseScore have any notion of the language being used for a given piece of text? We can restrict automatic ligatures to certain languages, but that may not solve the problem in this case.

**Comment by Jojo-Schmitz** [comment]
Having that ligature is not an issue at all, automatically convertine a "Nr." into that though is an issue, in all languages that don't abbreviate "Number" or "Nummer", as "No" but as "Nr."

**Comment by Jojo-Schmitz** [comment]
Having that glyph is not an issue at all, automatically converting a "Nr." into that though is an issue, in all languages that don't abbreviate "Number" or "Nummer", as "No" but as "Nr."
Automatically change "No." onto that ligature might be OK though?

**Comment by oktophonie** [comment]
In English we use "No." but never №, so we'd just end up annoying English speakers rather than German speakers :)

Russian users, who are most likely to use it, have access to the symbol directly from their keyboard (Shift-3).

Given that this represents a new and confusing behaviour from a MuseScore point of view (e.g. if people have changed font from FreeSerif, which doesn't include this ligature), I'll remove it from Edwin.

I feel the simplest solution is to remove the ligature definition. Russian users, who are most likely to want it, have access to the symbol directly from their keyboard (Shift-3).

**Comment by Jojo-Schmitz** [comment]
Better annoy English speakers rather than German speakers  ;-)

**Comment by maximebochon** [comment]
It is used in French too, I think.

Keeping the glyph in the font but disabling the "Nr." ligature seems good to me, thus users can have a choice between "Nr." and "№" unicode character.

**Comment by Jojo-Schmitz** [comment]
Yes, Romance languages do this, in addition tp Russian

**Comment by oktophonie** [comment]
Fixed in [0.53](https://github.com/MuseScoreFonts/Edwin/releases/tag/v0.53)
