### ISSUE TITLE
Vietnamese support

### ISSUE THREAD

**Issue by tommai4881** [MuseScoreFonts/Edwin#7]
This font lacks support for Vietnamese!

**Comment by oktophonie** [comment]
Edwin is not intended to cover all character sets (at least not at the moment), as this would be an enormous project. However, a free font that is extremely similar and which includes Vietnamese characters is [TEX Gyre Schola](https://ctan.org/pkg/tex-gyre-schola).

**Comment by Jojo-Schmitz** [comment]
But Edwin is supposed to replace FreeSerif, and that does support Vietnamese, as far as I can tell.
Can't you just copy the glyphs from either that TEX Gyre Schola or FreeSerif into Edwin?

**Comment by tommai4881** [comment]
Ahhh... that's a good idea...

Vào Th 4, 10 thg 11, 2021 vào lúc 17:17 Joachim Schmitz <
***@***.***> đã viết:

**Comment by oktophonie** [comment]
Edwin is not a total replacement for FreeSerif. FreeSerif is still available and can be used in MuseScore.
We would have preferred to base Edwin on TeX Gyre Schola (as it's more complete) but the licence was problematic. Copying the glyphs from FreeSerif is a poor solution as they would not match the other roman characters.

**Comment by Jojo-Schmitz** [comment]
Ah, right, I forgot that FreeSerif is still builtin.
