### ISSUE TITLE
Versiculum and Responsorium Unicode glyphs

### ISSUE THREAD

**Issue by santiclear** [MuseScoreFonts/Edwin#9]
Hello, I thought that it would be useful to include support for the 2123 (℣) and 211F (℟) glyphs, which are used to lay out liturgical texts set to music. 

Here'se a preview of what they look like in other open source fonts.

![image](https://user-images.githubusercontent.com/98980753/152413590-c58c46e9-d1ae-4149-a505-00362c3372f7.png)

**Comment by oktophonie** [comment]
Hello @Tantacrul, fancy it? ;)

**Comment by Tantacrul** [comment]
Yep, I'll get on it.

**Comment by santiclear** [comment]
Just for reference, I've seen more decorative versions of this glyph. But it is too humanist, it would not fit Edwin.

![image](https://user-images.githubusercontent.com/98980753/153056588-9dec0058-8331-4d6f-81af-f5f15c032551.png)

**Comment by Tantacrul** [comment]
It is surprisingly close to what I was thinking.

![image](https://user-images.githubusercontent.com/21022311/153067744-96fe8402-6cbf-432e-a374-8ec6e4addf8d.png)

I may try a version with the curve on the bottom too.

**Comment by santiclear** [comment]
It looks good. I wonder what it might look like with a curve (or even a rounded ending, like the tip of 2, $ and J) at the bottom, as well. It would give it a more calligraphic quality, which wouldn't be bad for a glyph meant to highlight the beginning of a text section.

On the other hand, as you said commenting the treble clef in your Leland video, context is important, and I am not sure whether such a choice would compliment the rest of the typeface, which is no-nonsense and seems to be using such features in order to help visually distinguishing similar letters (see the difference between the $ and S, or 3 and 8).

**Comment by Tantacrul** [comment]
Oh, I tried it a day or two ago and thought it looked weird.

<img width="397" alt="image" src="https://user-images.githubusercontent.com/21022311/153489136-f43b72f7-9710-4bb6-baba-768b3e8a5b37.png">

I think it's weird because Edwin already has a lot of detail and the additional flourishes are slightly noisy.

**Comment by santiclear** [comment]
I think you are right. Edwin has a lot of detail, but at the same time all that detail is unobtrusive - you basically do not even notice it, you just read the text. The first version is probably the best.

I only wonder whether it wouldn't fit in better with a fully round "hook". But then I have no training in type design.

![image](https://user-images.githubusercontent.com/98980753/153497209-396d6b07-d8e0-46db-9a78-eb15cf8a7a3d.png)

**Comment by ghost** [comment]
Added in [v0.54](https://github.com/MuseScoreFonts/Edwin/releases/tag/v0.54)
